export interface ThemePalette {
  background: string;
  homeBackground: string;
  surface: string;
  surfaceSecondary: string;
  text: string;
  textSecondary: string;
  textMuted: string;
  title: string;
  titleLogin: string;
  subtitle: string;
  accent: string;
  header: string;
  headerText: string;
  border: string;
  input: string;
  inputText: string;
  link: string;
  error: string;
  pageTitle: string;
  logoContainer: string;
  rulesBox: string;
  rulesBoxBorder: string;
  rankHighlight: string;
  postImageBg: string;
  avatarAlt: string;
  switchOff: string;
  switchKnob: string;
  imagePlaceholder: string;
  fab: string;
  chatBackground: string;
  chatBubbleOther: string;
  chatInputBar: string;
  chatInput: string;
  chatTextOther: string;
  chatName: string;
  white: string;
}

export const lightPalette: ThemePalette = {
  background: '#F5F5F5',
  homeBackground: '#9C9C9C',
  surface: '#FFFFFF',
  surfaceSecondary: '#F0F0F0',
  text: '#333333',
  textSecondary: '#666666',
  textMuted: '#999999',
  title: '#0B2046',
  titleLogin: '#001F3F',
  subtitle: '#666666',
  accent: '#00585C',
  header: '#00585C',
  headerText: '#FFFFFF',
  border: '#E0E0E0',
  input: '#F5F5F5',
  inputText: '#111111',
  link: '#00585C',
  error: '#D32F2F',
  pageTitle: '#FFFFFF',
  logoContainer: '#F0F0F0',
  rulesBox: '#FFF8F0',
  rulesBoxBorder: '#FFE0B2',
  rankHighlight: '#FFF3E0',
  postImageBg: '#333333',
  avatarAlt: '#E0E0E0',
  switchOff: '#CCCCCC',
  switchKnob: '#919191',
  imagePlaceholder: '#DDDDDD',
  fab: '#00585C',
  chatBackground: '#F5F5F5',
  chatBubbleOther: '#FFFFFF',
  chatInputBar: '#FFFFFF',
  chatInput: '#F0F0F0',
  chatTextOther: '#333333',
  chatName: '#0B2046',
  white: '#FFFFFF',
};

export const darkPalette: ThemePalette = {
  background: '#121212',
  homeBackground: '#1A1A1A',
  surface: '#2A2A2A',
  surfaceSecondary: '#333333',
  text: '#E0E0E0',
  textSecondary: '#AAAAAA',
  textMuted: '#888888',
  title: '#FFFFFF',
  titleLogin: '#FFFFFF',
  subtitle: '#AAAAAA',
  accent: '#00A896',
  header: '#003D40',
  headerText: '#FFFFFF',
  border: '#444444',
  input: '#333333',
  inputText: '#FFFFFF',
  link: '#00A896',
  error: '#EF5350',
  pageTitle: '#FFFFFF',
  logoContainer: '#333333',
  rulesBox: '#2D2A26',
  rulesBoxBorder: '#4A4030',
  rankHighlight: '#2D2520',
  postImageBg: '#1A1A1A',
  avatarAlt: '#555555',
  switchOff: '#555555',
  switchKnob: '#888888',
  imagePlaceholder: '#444444',
  fab: '#008B8F',
  chatBackground: '#121212',
  chatBubbleOther: '#2A2A2A',
  chatInputBar: '#1E1E1E',
  chatInput: '#333333',
  chatTextOther: '#E0E0E0',
  chatName: '#FFFFFF',
  white: '#FFFFFF',
};
