import { StyleSheet } from 'react-native';
import { ThemePalette } from '../theme/palette';

export const createStyles = (c: ThemePalette) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: c.background,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    card: {
      backgroundColor: c.surface,
      width: '90%',
      padding: 20,
      borderRadius: 10,
      flexDirection: 'column',
      gap: 15,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 10,
      elevation: 5,
    },
    logoContainer: {
      width: 80,
      height: 80,
      backgroundColor: c.logoContainer,
      borderRadius: 40,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 10,
      overflow: 'hidden',
    },
    logoImage: {
      width: 80,
      height: 80,
      borderRadius: 40,
      resizeMode: 'cover',
    },
    title: {
      fontSize: 24,
      fontWeight: 'bold',
      color: c.titleLogin,
      marginBottom: 5,
    },
    subtitle: {
      fontSize: 14,
      color: c.subtitle,
      marginBottom: 30,
    },
    label: {
      alignSelf: 'flex-start',
      fontSize: 14,
      fontWeight: 'bold',
      color: c.text,
      marginBottom: 5,
    },
    input: {
      width: '100%',
      backgroundColor: c.input,
      borderRadius: 8,
      padding: 12,
      marginBottom: 20,
      fontSize: 16,
      color: c.inputText,
    },
    button: {
      width: '100%',
      backgroundColor: c.accent,
      padding: 15,
      borderRadius: 8,
      alignItems: 'center',
      marginTop: 10,
      marginBottom: 20,
    },
    buttonText: {
      color: c.white,
      fontSize: 16,
      fontWeight: 'bold',
    },
    linkText: {
      color: c.link,
      fontSize: 14,
      fontWeight: '600',
    },
    errorText: {
      width: '100%',
      color: c.error,
      fontSize: 14,
      fontWeight: '600',
      marginTop: -10,
      marginBottom: 5,
    },
    homeContainer: {
      flex: 1,
      backgroundColor: c.homeBackground,
    },
    header: {
      backgroundColor: c.header,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingTop: 50,
      paddingBottom: 15,
      paddingHorizontal: 20,
      borderBottomLeftRadius: 15,
      borderBottomRightRadius: 15,
    },
    headerLogo: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    logoCircle: {
      backgroundColor: c.white,
      width: 35,
      height: 35,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
      overflow: 'hidden',
    },
    headerLogoImage: {
      width: 35,
      height: 35,
      borderRadius: 18,
      resizeMode: 'cover',
    },
    headerTitle: {
      color: c.headerText,
      fontSize: 20,
      fontWeight: 'bold',
    },
    headerIcons: {
      flexDirection: 'row',
    },
    icon: {
      marginLeft: 15,
      color: c.headerText,
    },
    pageTitle: {
      fontSize: 22,
      fontWeight: 'bold',
      color: c.pageTitle,
      margin: 20,
    },
    groupCard: {
      flexDirection: 'row',
      backgroundColor: c.surface,
      marginHorizontal: 20,
      marginBottom: 15,
      borderRadius: 12,
      padding: 10,
      alignItems: 'center',
      elevation: 3,
      shadowColor: '#000',
      shadowOpacity: 0.1,
      shadowRadius: 5,
      shadowOffset: { width: 0, height: 2 },
    },
    groupCardImage: {
      width: 70,
      height: 70,
      borderRadius: 10,
    },
    groupCardInfo: {
      flex: 1,
      marginLeft: 15,
    },
    groupCardTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: c.title,
      marginBottom: 5,
    },
    groupCardRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 3,
    },
    groupCardText: {
      fontSize: 13,
      color: c.textSecondary,
      marginLeft: 5,
    },
    btnSair: {
      padding: 5,
      marginLeft: 10,
    },
    fab: {
      position: 'absolute',
      right: 20,
      bottom: 30,
      backgroundColor: c.fab,
      width: 60,
      height: 60,
      borderRadius: 30,
      alignItems: 'center',
      justifyContent: 'center',
      elevation: 5,
      shadowColor: '#000',
      shadowOpacity: 0.3,
      shadowRadius: 5,
      shadowOffset: { width: 0, height: 3 },
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContainer: {
      backgroundColor: c.surface,
      width: '85%',
      borderRadius: 12,
      padding: 20,
      elevation: 5,
      shadowColor: '#000',
      shadowOpacity: 0.25,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: c.title,
    },
    modalCloseBtn: {
      padding: 5,
    },
    modalActionBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 15,
      paddingHorizontal: 15,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 8,
      marginBottom: 12,
    },
    modalActionIcon: {
      marginRight: 15,
    },
    modalActionText: {
      fontSize: 16,
      color: c.title,
      fontWeight: '500',
    },
    grupoHeaderTop: {
      backgroundColor: c.header,
      flexDirection: 'row',
      alignItems: 'center',
      paddingTop: 50,
      paddingBottom: 15,
      paddingHorizontal: 20,
    },
    grupoHeaderTitle: {
      color: c.headerText,
      fontSize: 20,
      fontWeight: 'bold',
      marginLeft: 15,
    },
    grupoCover: {
      backgroundColor: '#1C2026',
      padding: 20,
      alignItems: 'flex-start',
      justifyContent: 'flex-end',
      minHeight: 120,
      overflow: 'hidden',
    },
    grupoCoverImage: {
      ...StyleSheet.absoluteFillObject,
      width: '100%',
      height: '100%',
    },
    grupoCoverOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0, 0, 0, 0.45)',
    },
    grupoCoverContent: {
      width: '100%',
      zIndex: 1,
    },
    grupoCoverText: {
      color: '#CCC',
      fontSize: 14,
      marginTop: 5,
    },
    grupoCapaPreview: {
      width: '100%',
      height: 140,
      borderRadius: 10,
      backgroundColor: c.surfaceSecondary,
      marginBottom: 12,
      overflow: 'hidden',
      justifyContent: 'center',
      alignItems: 'center',
    },
    grupoCapaBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.input,
      borderRadius: 8,
      padding: 12,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: c.border,
      borderStyle: 'dashed',
    },
    grupoRegrasBox: {
      backgroundColor: c.rulesBox,
      borderRadius: 8,
      padding: 12,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: c.rulesBoxBorder,
    },
    grupoRegrasTitulo: {
      fontSize: 14,
      fontWeight: 'bold',
      color: c.title,
      marginBottom: 10,
    },
    grupoSwitchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    tabsContainer: {
      flexDirection: 'row',
      backgroundColor: c.surface,
      borderBottomWidth: 1,
      borderColor: c.border,
    },
    tab: {
      flex: 1,
      paddingVertical: 15,
      alignItems: 'center',
    },
    tabActive: {
      borderBottomWidth: 3,
      borderColor: c.accent,
    },
    tabText: {
      fontSize: 16,
      color: c.textSecondary,
      fontWeight: '500',
    },
    tabTextActive: {
      color: c.title,
      fontWeight: 'bold',
    },
    postCard: {
      backgroundColor: c.surface,
      margin: 15,
      borderRadius: 12,
      padding: 15,
      elevation: 3,
      shadowColor: '#000',
      shadowOpacity: 0.1,
      shadowRadius: 5,
      shadowOffset: { width: 0, height: 2 },
    },
    postHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
    },
    postAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: c.accent,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    postImagePlaceholder: {
      width: '100%',
      height: 200,
      backgroundColor: c.postImageBg,
      borderRadius: 8,
      marginBottom: 10,
    },
    postTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: c.title,
    },
    postDesc: {
      fontSize: 14,
      color: c.textSecondary,
      marginTop: 5,
      marginBottom: 10,
    },
    postActions: {
      flexDirection: 'row',
      gap: 15,
    },
    rankCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: c.surface,
      marginHorizontal: 15,
      marginTop: 10,
      padding: 15,
      borderRadius: 12,
      elevation: 2,
    },
    rankCardDestaque: {
      backgroundColor: c.rankHighlight,
      borderColor: c.accent,
      borderWidth: 1,
    },
    rankPos: {
      width: 30,
      fontSize: 18,
      fontWeight: 'bold',
      color: c.title,
    },
  });

export const createChatStyles = (c: ThemePalette) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: c.chatBackground },
    header: {
      backgroundColor: c.header,
      paddingTop: 50,
      paddingBottom: 15,
      paddingHorizontal: 15,
      flexDirection: 'row',
      alignItems: 'center',
    },
    avatarGrupo: { width: 40, height: 40, borderRadius: 20, marginLeft: 15 },
    tituloHeader: { color: c.headerText, fontSize: 18, fontWeight: 'bold', marginLeft: 10, flex: 1 },
    loading: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    lista: { padding: 15 },
    emptyText: { color: c.textMuted, textAlign: 'center', marginTop: 40 },
    msgContainer: { flexDirection: 'row', marginBottom: 15, alignItems: 'flex-end' },
    msgEsquerda: { justifyContent: 'flex-start' },
    msgDireita: { justifyContent: 'flex-end' },
    avatarUser: { width: 30, height: 30, borderRadius: 15, marginRight: 8 },
    balao: { maxWidth: '70%', padding: 12, borderRadius: 15 },
    balaoMeu: { backgroundColor: c.accent },
    balaoOutro: { backgroundColor: c.chatBubbleOther },
    textoMeu: { color: c.white },
    textoOutro: { color: c.chatTextOther },
    nomeUser: { fontSize: 10, fontWeight: 'bold', color: c.chatName, marginBottom: 2 },
    hora: { fontSize: 9, color: c.textMuted, textAlign: 'right', marginTop: 4 },
    inputContainer: {
      flexDirection: 'row',
      padding: 10,
      backgroundColor: c.chatInputBar,
      borderTopWidth: 1,
      borderColor: c.border,
    },
    input: {
      flex: 1,
      backgroundColor: c.chatInput,
      borderRadius: 20,
      paddingHorizontal: 15,
      marginRight: 10,
      color: c.inputText,
    },
    botaoEnviar: {
      backgroundColor: c.accent,
      width: 44,
      height: 44,
      borderRadius: 22,
      justifyContent: 'center',
      alignItems: 'center',
    },
  });

export type AppStyles = ReturnType<typeof createStyles>;
export type ChatStyles = ReturnType<typeof createChatStyles>;
